# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed_mogc <- function(seed) {
    invisible(.Call('_MOGC_set_seed_mogc', PACKAGE = 'MOGC', seed))
}

update_z_mogc <- function(N, P, K, z, pi_k, sigma2, mu, Y, Prob_Assign, debug) {
    invisible(.Call('_MOGC_update_z_mogc', PACKAGE = 'MOGC', N, P, K, z, pi_k, sigma2, mu, Y, Prob_Assign, debug))
}

get_nk_mogc <- function(N, K, z) {
    .Call('_MOGC_get_nk_mogc', PACKAGE = 'MOGC', N, K, z)
}

update_pi_k_mogc <- function(K, nk, alpha0, pi_k) {
    invisible(.Call('_MOGC_update_pi_k_mogc', PACKAGE = 'MOGC', K, nk, alpha0, pi_k))
}

update_mu_mogc <- function(P, P_dup, K, g_index, l_index, feature_dup_index, gamma_j, gamma_g, gamma_l, b) {
    .Call('_MOGC_update_mu_mogc', PACKAGE = 'MOGC', P, P_dup, K, g_index, l_index, feature_dup_index, gamma_j, gamma_g, gamma_l, b)
}

update_gamma_l_mogc <- function(P_dup, N, K, m2, g_index, l_index, nk, z, feature_dup_index, pi_l, sigma2, gamma_j, gamma_g, gamma_l, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_l_mogc', PACKAGE = 'MOGC', P_dup, N, K, m2, g_index, l_index, nk, z, feature_dup_index, pi_l, sigma2, gamma_j, gamma_g, gamma_l, b, mu, Y))
}

update_gamma_g_mogc <- function(P_dup, N, K, m1, BernoulliWeighted_int, g_index, l_index, l_index_g, nk, z, feature_dup_index, sigma2, weight_for_Dg, gamma_j, gamma_g, gamma_l, pi_g, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_g_mogc', PACKAGE = 'MOGC', P_dup, N, K, m1, BernoulliWeighted_int, g_index, l_index, l_index_g, nk, z, feature_dup_index, sigma2, weight_for_Dg, gamma_j, gamma_g, gamma_l, pi_g, b, mu, Y))
}

update_gamma_j_mogc <- function(P_dup, N, K, BernoulliWeighted_int, g_index, l_index, nk, z, feature_dup_index, sigma2, weight_for_Tj, gamma_j, gamma_g, gamma_l, pi_j, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_j_mogc', PACKAGE = 'MOGC', P_dup, N, K, BernoulliWeighted_int, g_index, l_index, nk, z, feature_dup_index, sigma2, weight_for_Tj, gamma_j, gamma_g, gamma_l, pi_j, b, mu, Y))
}

update_b_mogc <- function(P_dup, N, K, s2, g_index, l_index, nk, z, feature_dup_index, types, sigma2, gamma_j, gamma_g, gamma_l, b, mu, Y) {
    invisible(.Call('_MOGC_update_b_mogc', PACKAGE = 'MOGC', P_dup, N, K, s2, g_index, l_index, nk, z, feature_dup_index, types, sigma2, gamma_j, gamma_g, gamma_l, b, mu, Y))
}

update_sigma2_mogc <- function(P, N, z, sigma2, mu, Y) {
    invisible(.Call('_MOGC_update_sigma2_mogc', PACKAGE = 'MOGC', P, N, z, sigma2, mu, Y))
}

update_pi_l_mogc <- function(K, m2, pi_l, gamma_l) {
    invisible(.Call('_MOGC_update_pi_l_mogc', PACKAGE = 'MOGC', K, m2, pi_l, gamma_l))
}

update_pi_g_mogc <- function(P, m2, m1, K, BernoulliWeighted_int, MH_ind, pi_g_prop_n, gl, l_index_g, weight_for_Dg, gamma_g, pi_g, pi_g_loglikeli) {
    invisible(.Call('_MOGC_update_pi_g_mogc', PACKAGE = 'MOGC', P, m2, m1, K, BernoulliWeighted_int, MH_ind, pi_g_prop_n, gl, l_index_g, weight_for_Dg, gamma_g, pi_g, pi_g_loglikeli))
}

update_pi_j_mogc <- function(P_dup, m1, K, BernoulliWeighted_int, MH_ind, pi_j_prop_n, pg, g_index, weight_for_Tj, gamma_j, pi_j, pi_j_loglikeli) {
    invisible(.Call('_MOGC_update_pi_j_mogc', PACKAGE = 'MOGC', P_dup, m1, K, BernoulliWeighted_int, MH_ind, pi_j_prop_n, pg, g_index, weight_for_Tj, gamma_j, pi_j, pi_j_loglikeli))
}

update_s2_mogc <- function(P_dup, K, T, uni_types, types, feature_dup_index, s2, b) {
    invisible(.Call('_MOGC_update_s2_mogc', PACKAGE = 'MOGC', P_dup, K, T, uni_types, types, feature_dup_index, s2, b))
}

MCMC_mogc <- function(seed, burnInIter, keepIter, print_int, N, P, P_dup, m1, m2, K, BernoulliWeighted_int, MH_ind, s2, pi_g_prop_n, pi_j_prop_n, uni_types, types, g_index, l_index, l_index_g, pg, pl, gl, z, nk, feature_dup_index, alpha0, pi_j, pi_g, pi_l, sigma2, pi_k, weight_for_Dg, weight_for_Tj, gamma_j, gamma_g, gamma_l, b, mu, Y, debug, fix_z, fix_mu, pi_g_loglikeli, pi_j_loglikeli, s2_fixed) {
    .Call('_MOGC_MCMC_mogc', PACKAGE = 'MOGC', seed, burnInIter, keepIter, print_int, N, P, P_dup, m1, m2, K, BernoulliWeighted_int, MH_ind, s2, pi_g_prop_n, pi_j_prop_n, uni_types, types, g_index, l_index, l_index_g, pg, pl, gl, z, nk, feature_dup_index, alpha0, pi_j, pi_g, pi_l, sigma2, pi_k, weight_for_Dg, weight_for_Tj, gamma_j, gamma_g, gamma_l, b, mu, Y, debug, fix_z, fix_mu, pi_g_loglikeli, pi_j_loglikeli, s2_fixed)
}

set_seed_mogc_dp <- function(seed) {
    invisible(.Call('_MOGC_set_seed_mogc_dp', PACKAGE = 'MOGC', seed))
}

update_z_mogc_dp <- function(N, P, K, z, pi_k, sigma2, mu, Y, Prob_Assign, debug) {
    invisible(.Call('_MOGC_update_z_mogc_dp', PACKAGE = 'MOGC', N, P, K, z, pi_k, sigma2, mu, Y, Prob_Assign, debug))
}

get_nk_mogc_dp <- function(N, K, z) {
    .Call('_MOGC_get_nk_mogc_dp', PACKAGE = 'MOGC', N, K, z)
}

update_v_mogc_dp <- function(K, alpha_dp, nk, v) {
    invisible(.Call('_MOGC_update_v_mogc_dp', PACKAGE = 'MOGC', K, alpha_dp, nk, v))
}

update_pi_k_mogc_dp <- function(K, v, pi_k) {
    invisible(.Call('_MOGC_update_pi_k_mogc_dp', PACKAGE = 'MOGC', K, v, pi_k))
}

update_alpha_dp_mogc_dp <- function(K, alpha_dp, eta1, eta2, v) {
    .Call('_MOGC_update_alpha_dp_mogc_dp', PACKAGE = 'MOGC', K, alpha_dp, eta1, eta2, v)
}

update_mu_mogc_dp <- function(P, P_dup, K, g_index, l_index, feature_dup_index, gamma_j, gamma_g, gamma_l, b) {
    .Call('_MOGC_update_mu_mogc_dp', PACKAGE = 'MOGC', P, P_dup, K, g_index, l_index, feature_dup_index, gamma_j, gamma_g, gamma_l, b)
}

update_gamma_l_mogc_dp <- function(P_dup, N, K, m2, g_index, l_index, nk, z, feature_dup_index, pi_l, sigma2, gamma_j, gamma_g, gamma_l, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_l_mogc_dp', PACKAGE = 'MOGC', P_dup, N, K, m2, g_index, l_index, nk, z, feature_dup_index, pi_l, sigma2, gamma_j, gamma_g, gamma_l, b, mu, Y))
}

update_gamma_g_mogc_dp <- function(P_dup, N, K, m1, BernoulliWeighted_int, g_index, l_index, l_index_g, nk, z, feature_dup_index, sigma2, weight_for_Dg, gamma_j, gamma_g, gamma_l, pi_g, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_g_mogc_dp', PACKAGE = 'MOGC', P_dup, N, K, m1, BernoulliWeighted_int, g_index, l_index, l_index_g, nk, z, feature_dup_index, sigma2, weight_for_Dg, gamma_j, gamma_g, gamma_l, pi_g, b, mu, Y))
}

update_gamma_j_mogc_dp <- function(P_dup, N, K, BernoulliWeighted_int, g_index, l_index, nk, z, feature_dup_index, sigma2, weight_for_Tj, gamma_j, gamma_g, gamma_l, pi_j, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_j_mogc_dp', PACKAGE = 'MOGC', P_dup, N, K, BernoulliWeighted_int, g_index, l_index, nk, z, feature_dup_index, sigma2, weight_for_Tj, gamma_j, gamma_g, gamma_l, pi_j, b, mu, Y))
}

update_b_mogc_dp <- function(P_dup, N, K, s2, g_index, l_index, nk, z, feature_dup_index, types, sigma2, gamma_j, gamma_g, gamma_l, b, mu, Y) {
    invisible(.Call('_MOGC_update_b_mogc_dp', PACKAGE = 'MOGC', P_dup, N, K, s2, g_index, l_index, nk, z, feature_dup_index, types, sigma2, gamma_j, gamma_g, gamma_l, b, mu, Y))
}

update_sigma2_mogc_dp <- function(P, N, z, sigma2, mu, Y) {
    invisible(.Call('_MOGC_update_sigma2_mogc_dp', PACKAGE = 'MOGC', P, N, z, sigma2, mu, Y))
}

update_pi_l_mogc_dp <- function(K, m2, pi_l, gamma_l) {
    invisible(.Call('_MOGC_update_pi_l_mogc_dp', PACKAGE = 'MOGC', K, m2, pi_l, gamma_l))
}

update_pi_g_mogc_dp <- function(P, m2, m1, K, BernoulliWeighted_int, MH_ind, pi_g_prop_n, gl, l_index_g, weight_for_Dg, gamma_g, pi_g, pi_g_loglikeli) {
    invisible(.Call('_MOGC_update_pi_g_mogc_dp', PACKAGE = 'MOGC', P, m2, m1, K, BernoulliWeighted_int, MH_ind, pi_g_prop_n, gl, l_index_g, weight_for_Dg, gamma_g, pi_g, pi_g_loglikeli))
}

update_pi_j_mogc_dp <- function(P_dup, m1, K, BernoulliWeighted_int, MH_ind, pi_j_prop_n, pg, g_index, weight_for_Tj, gamma_j, pi_j, pi_j_loglikeli) {
    invisible(.Call('_MOGC_update_pi_j_mogc_dp', PACKAGE = 'MOGC', P_dup, m1, K, BernoulliWeighted_int, MH_ind, pi_j_prop_n, pg, g_index, weight_for_Tj, gamma_j, pi_j, pi_j_loglikeli))
}

update_s2_mogc_dp <- function(P_dup, K, T, uni_types, types, feature_dup_index, s2, b) {
    invisible(.Call('_MOGC_update_s2_mogc_dp', PACKAGE = 'MOGC', P_dup, K, T, uni_types, types, feature_dup_index, s2, b))
}

MCMC_mogc_dp <- function(seed, burnInIter, keepIter, print_int, N, P, P_dup, m1, m2, K, BernoulliWeighted_int, MH_ind, s2, pi_g_prop_n, pi_j_prop_n, uni_types, types, eta1, eta2, alpha_dp, g_index, l_index, l_index_g, pg, pl, gl, z, nk, feature_dup_index, v, pi_j, pi_g, pi_l, sigma2, pi_k, weight_for_Dg, weight_for_Tj, gamma_j, gamma_g, gamma_l, b, mu, Y, debug, fix_z, fix_mu, pi_g_loglikeli, pi_j_loglikeli, s2_fixed) {
    .Call('_MOGC_MCMC_mogc_dp', PACKAGE = 'MOGC', seed, burnInIter, keepIter, print_int, N, P, P_dup, m1, m2, K, BernoulliWeighted_int, MH_ind, s2, pi_g_prop_n, pi_j_prop_n, uni_types, types, eta1, eta2, alpha_dp, g_index, l_index, l_index_g, pg, pl, gl, z, nk, feature_dup_index, v, pi_j, pi_g, pi_l, sigma2, pi_k, weight_for_Dg, weight_for_Tj, gamma_j, gamma_g, gamma_l, b, mu, Y, debug, fix_z, fix_mu, pi_g_loglikeli, pi_j_loglikeli, s2_fixed)
}

set_seed_sogc <- function(seed) {
    invisible(.Call('_MOGC_set_seed_sogc', PACKAGE = 'MOGC', seed))
}

update_z_sogc <- function(N, P, K, z, pi_c, sigma2, mu, Y, Prob_Assign, debug) {
    .Call('_MOGC_update_z_sogc', PACKAGE = 'MOGC', N, P, K, z, pi_c, sigma2, mu, Y, Prob_Assign, debug)
}

get_nk_sogc <- function(N, K, z) {
    .Call('_MOGC_get_nk_sogc', PACKAGE = 'MOGC', N, K, z)
}

update_pi_c_sogc <- function(K, nk, alpha0, pi_c) {
    invisible(.Call('_MOGC_update_pi_c_sogc', PACKAGE = 'MOGC', K, nk, alpha0, pi_c))
}

update_mu_sogc <- function(P, P_dup, K, g_index, feature_dup_index, gamma_g, gamma_j, b) {
    .Call('_MOGC_update_mu_sogc', PACKAGE = 'MOGC', P, P_dup, K, g_index, feature_dup_index, gamma_g, gamma_j, b)
}

update_gamma_g_sogc <- function(P_dup, N, K, G, g_index, nk, z, feature_dup_index, U1_rowsum, pi_g, sigma2, gamma_g, gamma_j, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_g_sogc', PACKAGE = 'MOGC', P_dup, N, K, G, g_index, nk, z, feature_dup_index, U1_rowsum, pi_g, sigma2, gamma_g, gamma_j, b, mu, Y))
}

update_gamma_j_sogc <- function(P_dup, N, K, BernoulliWeighted_int, g_index, pg, nk, z, feature_dup_index, U1_rowsum, sigma2, weight_for_Rj, gamma_g, gamma_j, pi_j, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_j_sogc', PACKAGE = 'MOGC', P_dup, N, K, BernoulliWeighted_int, g_index, pg, nk, z, feature_dup_index, U1_rowsum, sigma2, weight_for_Rj, gamma_g, gamma_j, pi_j, b, mu, Y))
}

update_b_sogc <- function(P_dup, N, K, s2, g_index, nk, z, feature_dup_index, U1_rowsum, types, sigma2, gamma_g, gamma_j, b, mu, Y) {
    invisible(.Call('_MOGC_update_b_sogc', PACKAGE = 'MOGC', P_dup, N, K, s2, g_index, nk, z, feature_dup_index, U1_rowsum, types, sigma2, gamma_g, gamma_j, b, mu, Y))
}

update_sigma2_sogc <- function(P, N, z, sigma2, mu, Y) {
    invisible(.Call('_MOGC_update_sigma2_sogc', PACKAGE = 'MOGC', P, N, z, sigma2, mu, Y))
}

update_pi_g_sogc <- function(K, G, pi_g, gamma_g) {
    invisible(.Call('_MOGC_update_pi_g_sogc', PACKAGE = 'MOGC', K, G, pi_g, gamma_g))
}

update_pi_j_sogc <- function(P_dup, G, K, BernoulliWeighted_int, MH_ind, pi_j_prop_n, pg, g_index, weight_for_Rj, gamma_j, pi_j, pi_j_loglikeli) {
    invisible(.Call('_MOGC_update_pi_j_sogc', PACKAGE = 'MOGC', P_dup, G, K, BernoulliWeighted_int, MH_ind, pi_j_prop_n, pg, g_index, weight_for_Rj, gamma_j, pi_j, pi_j_loglikeli))
}

update_s2_sogc <- function(P_dup, K, T, uni_types, types, feature_dup_index, s2, b) {
    invisible(.Call('_MOGC_update_s2_sogc', PACKAGE = 'MOGC', P_dup, K, T, uni_types, types, feature_dup_index, s2, b))
}

MCMC_sogc <- function(seed, burnInIter, keepIter, print_int, N, P, P_dup, G, K, BernoulliWeighted_int, MH_ind, s2, pi_j_prop_n, uni_types, types, g_index, pg, z, nk, feature_dup_index, U1_rowsum, alpha0, pi_g, sigma2, pi_c, weight_for_Rj, gamma_g, gamma_j, pi_j, b, mu, Y, debug, fix_z, fix_mu, pi_j_loglikeli, s2_fixed) {
    .Call('_MOGC_MCMC_sogc', PACKAGE = 'MOGC', seed, burnInIter, keepIter, print_int, N, P, P_dup, G, K, BernoulliWeighted_int, MH_ind, s2, pi_j_prop_n, uni_types, types, g_index, pg, z, nk, feature_dup_index, U1_rowsum, alpha0, pi_g, sigma2, pi_c, weight_for_Rj, gamma_g, gamma_j, pi_j, b, mu, Y, debug, fix_z, fix_mu, pi_j_loglikeli, s2_fixed)
}

set_seed_sogc_dp <- function(seed) {
    invisible(.Call('_MOGC_set_seed_sogc_dp', PACKAGE = 'MOGC', seed))
}

update_z_sogc_dp <- function(N, P, K, z, pi_c, sigma2, mu, Y, Prob_Assign, debug) {
    invisible(.Call('_MOGC_update_z_sogc_dp', PACKAGE = 'MOGC', N, P, K, z, pi_c, sigma2, mu, Y, Prob_Assign, debug))
}

get_nk_sogc_dp <- function(N, K, z) {
    .Call('_MOGC_get_nk_sogc_dp', PACKAGE = 'MOGC', N, K, z)
}

update_v_sogc_dp <- function(K, alpha_dp, nk, v) {
    invisible(.Call('_MOGC_update_v_sogc_dp', PACKAGE = 'MOGC', K, alpha_dp, nk, v))
}

update_pi_c_sogc_dp <- function(K, v, pi_c) {
    invisible(.Call('_MOGC_update_pi_c_sogc_dp', PACKAGE = 'MOGC', K, v, pi_c))
}

update_alpha_dp_sogc_dp <- function(K, alpha_dp, eta1, eta2, v) {
    .Call('_MOGC_update_alpha_dp_sogc_dp', PACKAGE = 'MOGC', K, alpha_dp, eta1, eta2, v)
}

update_mu_sogc_dp <- function(P, P_dup, K, g_index, feature_dup_index, gamma_g, gamma_j, b) {
    .Call('_MOGC_update_mu_sogc_dp', PACKAGE = 'MOGC', P, P_dup, K, g_index, feature_dup_index, gamma_g, gamma_j, b)
}

update_gamma_g_sogc_dp <- function(P_dup, N, K, G, g_index, nk, z, feature_dup_index, U1_rowsum, pi_g, sigma2, gamma_g, gamma_j, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_g_sogc_dp', PACKAGE = 'MOGC', P_dup, N, K, G, g_index, nk, z, feature_dup_index, U1_rowsum, pi_g, sigma2, gamma_g, gamma_j, b, mu, Y))
}

update_gamma_j_sogc_dp <- function(P_dup, N, K, BernoulliWeighted_int, g_index, pg, nk, z, feature_dup_index, U1_rowsum, sigma2, weight_for_Rj, gamma_g, gamma_j, pi_j, b, mu, Y) {
    invisible(.Call('_MOGC_update_gamma_j_sogc_dp', PACKAGE = 'MOGC', P_dup, N, K, BernoulliWeighted_int, g_index, pg, nk, z, feature_dup_index, U1_rowsum, sigma2, weight_for_Rj, gamma_g, gamma_j, pi_j, b, mu, Y))
}

update_b_sogc_dp <- function(P_dup, N, K, s2, g_index, nk, z, feature_dup_index, U1_rowsum, types, sigma2, gamma_g, gamma_j, b, mu, Y) {
    invisible(.Call('_MOGC_update_b_sogc_dp', PACKAGE = 'MOGC', P_dup, N, K, s2, g_index, nk, z, feature_dup_index, U1_rowsum, types, sigma2, gamma_g, gamma_j, b, mu, Y))
}

update_sigma2_sogc_dp <- function(P, N, z, sigma2, mu, Y) {
    invisible(.Call('_MOGC_update_sigma2_sogc_dp', PACKAGE = 'MOGC', P, N, z, sigma2, mu, Y))
}

update_pi_g_sogc_dp <- function(K, G, pi_g, gamma_g) {
    invisible(.Call('_MOGC_update_pi_g_sogc_dp', PACKAGE = 'MOGC', K, G, pi_g, gamma_g))
}

update_pi_j_sogc_dp <- function(P_dup, G, K, BernoulliWeighted_int, MH_ind, pi_j_prop_n, pg, g_index, weight_for_Rj, gamma_j, pi_j, pi_j_loglikeli) {
    invisible(.Call('_MOGC_update_pi_j_sogc_dp', PACKAGE = 'MOGC', P_dup, G, K, BernoulliWeighted_int, MH_ind, pi_j_prop_n, pg, g_index, weight_for_Rj, gamma_j, pi_j, pi_j_loglikeli))
}

update_s2_sogc_dp <- function(P_dup, K, T, uni_types, types, feature_dup_index, s2, b) {
    invisible(.Call('_MOGC_update_s2_sogc_dp', PACKAGE = 'MOGC', P_dup, K, T, uni_types, types, feature_dup_index, s2, b))
}

MCMC_sogc_dp <- function(seed, burnInIter, keepIter, print_int, N, P, P_dup, G, K, BernoulliWeighted_int, MH_ind, s2, pi_j_prop_n, uni_types, types, eta1, eta2, alpha_dp, g_index, pg, z, nk, feature_dup_index, U1_rowsum, v, pi_c, sigma2, weight_for_Rj, gamma_g, gamma_j, pi_g, pi_j, b, mu, Y, debug, fix_z, fix_mu, pi_j_loglikeli, s2_fixed) {
    .Call('_MOGC_MCMC_sogc_dp', PACKAGE = 'MOGC', seed, burnInIter, keepIter, print_int, N, P, P_dup, G, K, BernoulliWeighted_int, MH_ind, s2, pi_j_prop_n, uni_types, types, eta1, eta2, alpha_dp, g_index, pg, z, nk, feature_dup_index, U1_rowsum, v, pi_c, sigma2, weight_for_Rj, gamma_g, gamma_j, pi_g, pi_j, b, mu, Y, debug, fix_z, fix_mu, pi_j_loglikeli, s2_fixed)
}

rcppeigen_hello_world <- function() {
    .Call('_MOGC_rcppeigen_hello_world', PACKAGE = 'MOGC')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_MOGC_rcppeigen_outerproduct', PACKAGE = 'MOGC', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_MOGC_rcppeigen_innerproduct', PACKAGE = 'MOGC', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_MOGC_rcppeigen_bothproducts', PACKAGE = 'MOGC', x)
}

